### PR TITLE
Use scratch instead of project as the latter hit the file limit

### PR DESCRIPTION
**Pull request by ikbuibui**
Use /scratch to build alpaka instead of /project

### CODE REVIEW

**Comment by ikbuibui** [comment]
@mehmetyusufoglu can you please test the alpaka setup from scratch till running the vector add example, and then try running one of the timing branches
@franzpoeschel Could you check if this change is affecting you in some other way which is not addressed?

**Comment by franzpoeschel** [comment]
Let me clean up my build directories on /scratch, that should hopefully fix that

**Comment by franzpoeschel** [comment]
Also, if you load the environment at `/pfs/lustrep3/projappl/project_465001310/workshop_software`, that should already include an installation of Alpaka

**Comment by ikbuibui** [comment]
> Also, if you load the environment at `/pfs/lustrep3/projappl/project_465001310/workshop_software`, that should already include an installation of Alpaka

Since we do load that environment, does that mean that we dont need to give the prefix path in the cmake at all?

**Comment by franzpoeschel** [comment]
The `CMAKE_PREFIX_PATH` is modified by the environment, so you don't need to. If you use the environment, you should ideally not need to install anything on your own.
The build folder is now removed, that's many files gone now. Forgot removing it after last weeks reinstall.

**Comment by ikbuibui** [comment]
I will remove the manually added PATH. We will still install alpaka as we want to guide users through it, but it wont be used for the rest of the workshop

**Comment by franzpoeschel** [comment]
Sounds good. I didn't want to have users set up the dependencies manually, since I need HDF5, ADIOS2 and openPMD-api additionally, each of them with specific configuration, this would have been half a day of compiling only.

**Comment by ikbuibui** [comment]
Will merge once @mehmetyusufoglu tests and is happy

**Comment by franzpoeschel** [comment]
Would be good if someone tests the environment, to see if the permissions are set correctly

**Comment by mehmetyusufoglu** [comment]
somehow I get this error at any example compilation:

make
[ 50%] Building CXX object CMakeFiles/convolution1D.dir/src/convolution1D.cpp.o
/users/yusufogl/src/convolution1D/src/convolution1D.cpp:5:10: fatal error: 'alpaka/alpaka.hpp' file not found
#include <alpaka/alpaka.hpp>
         ^~~~~~~~~~~~~~~~~~~
1 error generated.

**Comment by ikbuibui** [comment]
interesting, I tried and I dont get any errors

**Comment by franzpoeschel** [comment]
@mehmetyusufoglu Maybe try opening a new shell and create a new build folder. Do you get the error with this PR or with the environment?

**Comment by mehmetyusufoglu** [comment]
> @mehmetyusufoglu Maybe try opening a new shell and create a new build folder. Do you get the error with this PR or with the environment?

Yes I still get errors. It is also reported today by a participant.

**Comment by ikbuibui** [comment]
@mehmetyusufoglu Is this PR still required to fix file limit issues?

**Pull request closed without merging**
