### PR TITLE
openPMD presentation feature-complete, some minor other fixes

### LINKED ISSUE #61: Typo in Day_2/13
@franzpoeschel I think you meant `ccmake .` and not `cmake .` in line 7 of https://github.com/alpaka-group/alpaka-workshop-slides/edit/oct2024_workshop/Day_2/13_streaming_io_solution/build/buildAndRun.md.

### PR DESCRIPTION
**Pull request by franzpoeschel**
This also fixes #61 @chillenzer

### CODE REVIEW

**Review by chillenzer — COMMENTED** [review]
On the slide "Example dataset: JSON/TOML backend": Would it be possible to make the flow of reading more clear, say with a dividing line between the two columns of code? Honestly, I'm not 100% sure how to interpret the json on there. I'm tempted to read it as first column, second column but then `"dataype": "VEC_STRING",` appears twice.

**Comment by chillenzer** [comment]
PS: Thanks for the fix!

**Comment by franzpoeschel** [comment]
I'll use a JSON dataset in shorthand notation. It's more legible, but technically still WIP

**Comment by franzpoeschel** [comment]
Done. Now also contains some further final touches.

**Pull request merged**
